name: Deploy to AWS ECS

on:
  push:
    branches:
      - main  # Run this workflow on every push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag Docker image
        env:
          REPO_URI: public.ecr.aws/j0h9z3j3/react/dream-ap
        run: |
          docker build -t $REPO_URI:latest .
          docker tag $REPO_URI:latest $REPO_URI:${{ github.sha }}

      - name: Push to Amazon ECR
        env:
          REPO_URI: public.ecr.aws/j0h9z3j3/react/dream-app
        run: |
          docker push $REPO_URI:latest
          docker push $REPO_URI:${{ github.sha }}

      - name: Deploy to Amazon ECS
        env:
          AWS_REGION: ap-southeast-2
          CLUSTER: deam
          SERVICE: dream
          IMAGE_URI: public.ecr.aws/j0h9z3j3/react/dream-ap:${{ github.sha }}
        run: |
          aws 
